### ISSUE TITLE
Bug in GetMaximumLoanAmountAsync

### ISSUE THREAD

**Issue by hcanak** [JKorf/OKX.Net#49]
Hello @JKorf ,

When i call GetMaximumLoanAmountAsync with following parameters it gives the error in picture...

_UnifiedApi.Account.GetMaximumLoanAmountAsync("BTC-USDT", OKX.Net.Enums.MarginMode.Isolated);_

![image](https://github.com/user-attachments/assets/da6e6ce2-ff3b-4357-8bb2-b67d96b318f7)

**Comment by JKorf** [comment]
Hi, there are 2 issues. The first is that error responses aren't parsed correctly causing this error. This has been fixed in the latest version, but I'm not yet able to release it on NuGet.
The second is that the serialization of the marginMode parameter is incorrect, which is why the server returns an error. I'll fix that one for next version.

**Comment by hcanak** [comment]
Thanks for your quick responce @JKorf

**Comment by JKorf** [comment]
Fixed in latest version
